### ISSUE TITLE
CSS 신기술과 라이브러리 트렌드

### ISSUE THREAD

**Issue by ed-jinyoung-park** [FEStudy-boostcamp/FEStudy#7]
# CSS 새로운 스펙

### Container queries
- https://developer.chrome.com/blog/whats-new-css-ui-2023/#container-queries
- 브라우저 viewport(media query)가 아닌 박스 viewport에 반응하는 css
- component 사이즈 기반으로 style 조절 가능
- cqw(container query width), cqh(container query height) 등 새로운 측정값도 등장
```css
.inbox {
  container: inbox / inline-size; /* container-name / container-type */
 /* container-type은 inline-size, size, normal이 있다 */
}

@container (width <= 550px) {
  .item {
    grid-template-columns: 3.5rem 1fr 4fr;
  }
  
  .time {
    display: none;
  }
}

```

### ``has`` selector
- https://developer.chrome.com/blog/has-m105/#how-to-use-has
- 특정 상태를 만족하는지 확인할 수 있는 selector
```css
<target>:has(<condition>) { <styles> }
```
```css
.card:has(.visual) {
  grid-template-columns: 1fr 1fr;
}

.card:not(:has(.visual)) h1 {
  font-size: 4rem;
}
```

### nth-of syntax
- ``:nth-child`` selector의 발전된 버전. 특정 selector 중 몇번째 child인지 새로운 조건을 걸 수 있음.
```css
:nth-child(2 of .special)
```

### nesting 기본 지원
- sass를 통해 지원되던 nesting을 css에서도 기본 지원
```css
.card {}
.card:hover {}

/* can be done with nesting like */
.card {
  &:hover {
    
  }
}

.card {
  display: grid;
  gap: 1rem;

  @container (width >= 480px) {
    display: flex;
  }
}
```

### scope
- 특정 scope안에만 css가 적용되는 기능.
- chrome 최신 버전만 지원 (https://caniuse.com/css-cascade-scope)
```css
@scope (.card) {
  .title { 
    font-weight: bold;
  }
}
```

### ``@property``
- https://developer.mozilla.org/en-US/docs/Web/CSS/@property
- css 변수에 default값을 부여하고 유형, 상속 여부 지정
```css
/* AS-IS */
html {
  --primaryColor: red;
}

.link {
  color: var(--primaryColor);
}

.link:hover {
  color: blue;
}

/* TO-BE */
@property --primaryColor {
   syntax: "<color">;  /* 변수의 유형 지정
   initital-value: red;  /* 기본값 지정 */
   inherits: false; /* dom tree 상속 여부 */
}

.link {
  color: var(--primaryColor);  /* red */
}

.link:hover {
  --primaryColor: blue; /* blue */
}

.link:fisrt-child:hover {
  --primaryColor: false; /* red */
}


```

### scroll-based animation css
- https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline
- 기존 time based animation에 더해 scroll based animation 을 추가 예정
- scroll시에 dom 변화는 js로만 다루어야 했던 패러다임을 바꿀 수 있는 스펙
